name: Build and Deploy to GitHub pages

on:
  push:
    branches: 
      - main

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}